- pipeline: deploy_netlify
  name: deploy-netlify
  refs:
  - refs/heads/main
  events:
  - type: PUSH
  fail_on_prepare_env_warning: true
  resources: NANO
  arch: ARM64
  actions:
  - action: netlify deploy --dir=. --prod
    type: NETLIFY
    version: 20
    site_id: demo-check-netlify
    integration: netlify
    execute_commands:
    - netlify deploy --dir=. --prod
    shell: BASH
